CLOUDERA-BUILD: Oozie Web UI shows HTTP Status 500: NoSuchMethodError (CDH-21928)
(cherry picked from commit 0ba03a75ccb4ec1927be9753e7163c664f21f182)